services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - reporting-db
  reporting-db:
    image: postgres:15
    environment:
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report
      POSTGRES_DB: reporting
    volumes:
      - reporting-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  reporting-db-data: