services:
  airbyte-webapp:
    image: airbyte/webapp:latest
    depends_on:
      - airbyte-server
    ports:
      - "8000:8000"

  airbyte-server:
    image: airbyte/server:latest
    depends_on:
      - airbyte-db
    environment:
      - CONFIG_DATABASE_USER=airbyte
      - CONFIG_DATABASE_PASSWORD=airbyte
      - CONFIG_DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
    ports:
      - "8001:8001"

  airbyte-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airbyte
      POSTGRES_PASSWORD: airbyte
      POSTGRES_DB: airbyte
    volumes:
      - airbyte-db-data:/var/lib/postgresql/data

volumes:
  airbyte-db-data: